project:
  type: website

website:
  title: "zhaolunfan.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true