---
title: "Research"
format: html
---

## Publications

### Peer-Reviewed Articles
- Fan, Z., Thouzeau, V., de Dampierre, C., Chevallier, C., & Baumard, N. (2025). Name uniqueness and the rise of individualism in the Western hemisphere (1500–2000). *Current Research in Ecological and Social Psychology, 9* (Special Issue: Historical Psychology), 100235 [Full Text](https://www.sciencedirect.com/science/article/pii/S266662272500022X)

### Working Papers
- Fan, Z., Thouzeau, V., Zhong, Y., Chevallier, C., & Baumard, N. (2025). Name uniqueness and the rise of individualism in Imperial China (540–1880 CE). Preprint available at [OSF](https://doi.org/10.31235/osf.io/62mvg) 

- Fan, Z., Thouzeau, V., Chevallier, C., & Baumard, N. (2025). Name uniqueness and individualism in France: A century of changes across 95 prefectures. Preprint available at [SocArXiv](https://osf.io/preprints/socarxiv/vg3qz_v1)  



## Invited Talks
- Fan, Z., Thouzeau, V., de Dampierre, C., Chevallier, C., & Baumard, N. (2025, July). Tracking individualism in the long term. Paper presented at the International Conference on Computational Social Science (IC2S2), Norrköping, Sweden.  

- Fan, Z., & Zheng, L. (2022, June). Social network and subjective well-being in collectivist societies: A comparison of China and Japan. Paper presented at the World Congress of Sociology of the International Sociological Association (ISA), Melbourne, Australia.  

- Fan, Z., Blasko, A., & Misheva, V. (2022, June). *Perceived health risk during the COVID-19 pandemic: A sociological approach.* Paper presented at the World Congress of Sociology of the International Sociological Association (ISA), Melbourne, Australia.  